---
abstract: 'Routines for text containing wide characters'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Test::More: 0.98
  blib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-WideChar-Util
requires:
  Unicode::GCString: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Text-WideChar-Util
  repository: http://github.com/sharyanto/perl-Text-WideChar-Util
version: 0.07
